In [1]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(4, 10)

array([10, 10, 10, 10])

In [6]:
np.array([2,5,6])

array([2, 5, 6])

In [7]:
np.arange(4, 20)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
a = np.array([[1,2,3,4],[5,6,7,8],[6, 6, 0, 5],])  

In [21]:
a[1,2] = 45

In [22]:
print(a)

[[ 1  2  3  4]
 [ 5  6 45  8]
 [ 6  6  0  5]]


In [23]:
print(a[2])

[6 6 0 5]


In [25]:
print(a[:,2])

[ 3 45  0]


In [26]:
a[:, 2] = [33,33, 33]
print(a)

[[ 1  2 33  4]
 [ 5  6 33  8]
 [ 6  6 33  5]]


In [27]:
np.random.rand(5,2)

array([[0.17407206, 0.93775492],
       [0.28580126, 0.29136132],
       [0.34277987, 0.65021895],
       [0.53978448, 0.78264464],
       [0.15557395, 0.37589132]])

In [ ]:
np.rn