In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('Telco-Customer-Churn.csv')
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [3]:
df.head().T

0             1               2  \
customerID              7590-VHVEG    5575-GNVDE      3668-QPYBK   
gender                      Female          Male            Male   
SeniorCitizen                    0             0               0   
Partner                        Yes            No              No   
Dependents                      No            No              No   
tenure                           1            34               2   
PhoneService                    No           Yes             Yes   
MultipleLines     No phone service            No              No   
InternetService                DSL           DSL             DSL   
OnlineSecurity                  No           Yes             Yes   
OnlineBackup                   Yes            No             Yes   
DeviceProtection                No           Yes              No   
TechSupport                     No            No              No   
StreamingTV                     No            No              No   
StreamingMovies                 No            No              No   
Contract            Month-to-month      One year  Month-to-month   
PaperlessBilling               Yes            No             Yes   
PaymentMethod     Electronic check  Mailed check    Mailed check   
MonthlyCharges               29.85         56.95           53.85   
TotalCharges                 29.85        1889.5          108.15   
Churn                           No            No             Yes   

                                          3                 4  
customerID                       7795-CFOCW        9237-HQITU  
gender                                 Male            Female  
SeniorCitizen                             0                 0  
Partner                                  No                No  
Dependents                               No                No  
tenure                                   45                 2  
PhoneService                             No               Yes  
MultipleLines              No phone service                No  
InternetService                         DSL       Fiber optic  
OnlineSecurity                          Yes                No  
OnlineBackup                             No                No  
DeviceProtection                        Yes                No  
TechSupport                             Yes                No  
StreamingTV                              No                No  
StreamingMovies                          No                No  
Contract                           One year    Month-to-month  
PaperlessBilling                         No               Yes  
PaymentMethod     Bank transfer (automatic)  Electronic check  
MonthlyCharges                         42.3              70.7  
TotalCharges                        1840.75            151.65  
Churn                                    No               Yes

In [25]:
list(df.columns)

['customerid',
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'monthlycharges',
 'totalcharges',
 'churn']

In [31]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

# df.dtypes[df.dtypes == 'object']

# list(df.dtypes[df.dtypes == 'object'])

# df.dtypes[df.dtypes == 'object'].index

categorical_columns = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical_columns:
    df[c] = df[c].str.lower().str.replace(" ", "_")

In [43]:
tc = pd.to_numeric(df['totalcharges'], errors="coerce")

df['totalcharges'] = tc

df['totalcharges'] = df['totalcharges'].fillna(0)

df[df['totalcharges']== 0][['customerid', 'totalcharges']]


customerid  totalcharges
488   4472-lvygi           0.0
753   3115-czmzd           0.0
936   5709-lvoeq           0.0
1082  4367-nuyao           0.0
1340  1371-dwpaz           0.0
3331  7644-omvmy           0.0
3826  3213-vvolg           0.0
4380  2520-sgtta           0.0
5218  2923-arzlg           0.0
6670  4075-wkniu           0.0
6754  2775-sefee           0.0

In [45]:
df.churn.head()

0     no
1     no
2    yes
3     no
4    yes
Name: churn, dtype: object

In [46]:
df.churn == "yes"

0       False
1       False
2        True
3       False
4        True
        ...  
7038    False
7039    False
7040    False
7041     True
7042    False
Name: churn, Length: 7043, dtype: bool

In [82]:
df.churn = (df.churn == 'yes').astype('int')

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
len(df_full_train), len(df_test)

(5634, 1409)

In [85]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [86]:
len(df_train), len(df_test), len(df_val)

(4225, 1409, 1409)

In [87]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)

In [88]:
y_train = df_train['churn'].values
y_val = df_val['churn'].values
y_test = df_test['churn'].values

In [89]:
del df_train['churn']
del df_val['churn']
del df_test['churn']

In [90]:
df_full_train = df_full_train.reset_index(drop=True)

In [91]:
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [92]:
df_full_train.churn.value_counts(normalize=True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [94]:
global_churn_rate = df_full_train.churn.mean()
round(global_churn_rate , 2)

0.27

In [96]:
df_full_train.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                 int64
dtype: object

In [97]:
numerical = ['tenure', 'monthlycharges', 'totalcharges']

In [103]:
list(df_full_train.columns)

['customerid',
 'gender',
 'seniorcitizen',
 'partner',
 'dependents',
 'tenure',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'monthlycharges',
 'totalcharges',
 'churn']

In [104]:
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents',
               'phoneservice', 'multiplelines', 'internetservice',
               'onlinesecurity', 'onlinebackup', 'deviceprotection',
               'techsupport', 'streamingtv', 'streamingmovies',
               'contract', 'paperlessbilling', 'paymentmethod']

In [105]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [111]:
female_mean = df_full_train[df_full_train.gender == 'female'].churn.mean()
print('gender == female:', female_mean)

gender == female: 0.27682403433476394


In [112]:
male_mean = df_full_train[df_full_train.gender == 'male'].churn.mean()
print('gender == male:', male_mean)

gender == male: 0.2632135306553911


In [117]:
from IPython.display import display

In [116]:
df_group = df_full_train.groupby('gender')['churn'].agg(['mean'])
df_group['diff'] = df_group['mean']- global_churn_rate
df_group['risk'] = df_group['mean'] / global_churn_rate
df_group

mean      diff      risk
gender                              
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

In [118]:
for col in categorical:
    df_group = df_full_train.groupby(col)['churn'].agg(['mean'])
    df_group['diff'] = df_group['mean']- global_churn_rate
    df_group['risk'] = df_group['mean'] / global_churn_rate
    display(df_group)

mean      diff      risk
gender                              
female  0.276824  0.006856  1.025396
male    0.263214 -0.006755  0.974980

mean      diff      risk
seniorcitizen                              
0              0.242270 -0.027698  0.897403
1              0.413377  0.143409  1.531208

mean      diff      risk
partner                              
no       0.329809  0.059841  1.221659
yes      0.205033 -0.064935  0.759472

mean      diff      risk
dependents                              
no          0.313760  0.043792  1.162212
yes         0.165666 -0.104302  0.613651

mean      diff      risk
phoneservice                              
no            0.241316 -0.028652  0.893870
yes           0.273049  0.003081  1.011412

mean      diff      risk
multiplelines                                 
no                0.257407 -0.012561  0.953474
no_phone_service  0.241316 -0.028652  0.893870
yes               0.290742  0.020773  1.076948

mean      diff      risk
internetservice                              
dsl              0.192347 -0.077621  0.712482
fiber_optic      0.425171  0.155203  1.574895
no               0.077805 -0.192163  0.288201

mean      diff      risk
onlinesecurity                                   
no                   0.420921  0.150953  1.559152
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.153226 -0.116742  0.567570

mean      diff      risk
onlinebackup                                     
no                   0.404323  0.134355  1.497672
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.217232 -0.052736  0.804660

mean      diff      risk
deviceprotection                                 
no                   0.395875  0.125907  1.466379
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.230412 -0.039556  0.853480

mean      diff      risk
techsupport                                      
no                   0.418914  0.148946  1.551717
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.159926 -0.110042  0.592390

mean      diff      risk
streamingtv                                      
no                   0.342832  0.072864  1.269897
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.302723  0.032755  1.121328

mean      diff      risk
streamingmovies                                  
no                   0.338906  0.068938  1.255358
no_internet_service  0.077805 -0.192163  0.288201
yes                  0.307273  0.037305  1.138182

mean      diff      risk
contract                                    
month-to-month  0.431701  0.161733  1.599082
one_year        0.120573 -0.149395  0.446621
two_year        0.028274 -0.241694  0.104730

mean      diff      risk
paperlessbilling                              
no                0.172071 -0.097897  0.637375
yes               0.338151  0.068183  1.252560

mean      diff      risk
paymentmethod                                          
bank_transfer_(automatic)  0.168171 -0.101797  0.622928
credit_card_(automatic)    0.164339 -0.105630  0.608733
electronic_check           0.455890  0.185922  1.688682
mailed_check               0.193870 -0.076098  0.718121

In [119]:
from sklearn.metrics import mutual_info_score


In [122]:
def calculate_mi(series):
    return mutual_info_score(series, df_full_train.churn)

df_mi = df_full_train[categorical].apply(calculate_mi)

df_mi

gender              0.000117
seniorcitizen       0.009410
partner             0.009968
dependents          0.012346
phoneservice        0.000229
multiplelines       0.000857
internetservice     0.055868
onlinesecurity      0.063085
onlinebackup        0.046923
deviceprotection    0.043453
techsupport         0.061032
streamingtv         0.031853
streamingmovies     0.031581
contract            0.098320
paperlessbilling    0.017589
paymentmethod       0.043210
dtype: float64

In [127]:
df_full_train[numerical].corrwith(df_full_train['churn']).to_frame('correlation')

correlation
tenure            -0.351885
monthlycharges     0.196805
totalcharges      -0.196353

In [132]:
df_full_train.groupby('churn')[numerical].mean()

tenure  monthlycharges  totalcharges
churn                                         
0      37.531972       61.176477   2548.021627
1      18.070348       74.521203   1545.689415

In [133]:
from sklearn.feature_extraction import DictVectorizer

In [153]:
train_dict = df_train[categorical+numerical].to_dict(orient='records')
val_dict = df_val[categorical+numerical].to_dict(orient='records')
train_dict

[{'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'yes',
  'streamingmovies': 'yes',
  'contract': 'two_year',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 72,
  'monthlycharges': 115.5,
  'totalcharges': 8425.15},
 {'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'yes',
  'internetservice': 'fiber_optic',
  'onlinesecurity': 'no',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'no',
  'streamingtv': 'no',
  'streamingmovies': 'yes',
  'contract': 'month-to-month',
  'paperlessbilling': 'yes',
  'paymentmethod': 'electronic_check',
  'tenure': 10,
  'monthlycharges': 95.25,
  'totalcharges': 1021.55},
 {'gender

In [146]:
dv = DictVectorizer(sparse=False)

In [163]:
dv.fit(train_dict)
X_train = dv.transform(train_dict)
# X_train = dv.fit_transform(train_dict)

X_train.shape


(4225, 45)

In [152]:
list(dv.get_feature_names_out())

['contract=month-to-month',
 'contract=one_year',
 'contract=two_year',
 'dependents=no',
 'dependents=yes',
 'deviceprotection=no',
 'deviceprotection=no_internet_service',
 'deviceprotection=yes',
 'gender=female',
 'gender=male',
 'internetservice=dsl',
 'internetservice=fiber_optic',
 'internetservice=no',
 'monthlycharges',
 'multiplelines=no',
 'multiplelines=no_phone_service',
 'multiplelines=yes',
 'onlinebackup=no',
 'onlinebackup=no_internet_service',
 'onlinebackup=yes',
 'onlinesecurity=no',
 'onlinesecurity=no_internet_service',
 'onlinesecurity=yes',
 'paperlessbilling=no',
 'paperlessbilling=yes',
 'partner=no',
 'partner=yes',
 'paymentmethod=bank_transfer_(automatic)',
 'paymentmethod=credit_card_(automatic)',
 'paymentmethod=electronic_check',
 'paymentmethod=mailed_check',
 'phoneservice=no',
 'phoneservice=yes',
 'seniorcitizen',
 'streamingmovies=no',
 'streamingmovies=no_internet_service',
 'streamingmovies=yes',
 'streamingtv=no',
 'streamingtv=no_internet_servic

In [154]:
X_val = dv.transform(val_dict)

In [157]:
from sklearn.linear_model import LogisticRegression

In [158]:
model = LogisticRegression()

In [164]:
model.fit(X_train, y_train)

LogisticRegression()

In [167]:
model.intercept_[0]

-0.10903521054753158

In [170]:
model.coef_[0].round(3)

array([ 0.475, -0.175, -0.408, -0.03 , -0.078,  0.063, -0.089, -0.081,
       -0.034, -0.073, -0.335,  0.316, -0.089,  0.004, -0.258,  0.141,
        0.009,  0.063, -0.089, -0.081,  0.266, -0.089, -0.284, -0.231,
        0.124, -0.166,  0.058, -0.087, -0.032,  0.07 , -0.059,  0.141,
       -0.249,  0.215, -0.12 , -0.089,  0.102, -0.071, -0.089,  0.052,
        0.213, -0.089, -0.232, -0.07 ,  0.   ])

In [171]:
model.predict(X_val)

array([0, 0, 0, ..., 0, 1, 1])

In [172]:
model.predict_proba(X_val)

array([[0.99100278, 0.00899722],
       [0.79548139, 0.20451861],
       [0.7877827 , 0.2122173 ],
       ...,
       [0.86360882, 0.13639118],
       [0.20023445, 0.79976555],
       [0.16259705, 0.83740295]])

In [173]:
y_pred = model.predict_proba(X_val)[:,1]

In [175]:
churn_desc = (y_pred >= 0.5)

In [176]:
churn_desc

array([False, False, False, ..., False,  True,  True])

In [177]:
df_val[churn_desc]

customerid  gender  seniorcitizen partner dependents  tenure  \
3     8433-wxgna    male              0      no         no       2   
8     3440-jpscl  female              0      no         no       6   
11    2637-fkfsy  female              0     yes         no       3   
12    7228-omtpn    male              0      no         no       4   
19    6711-fldfb  female              0      no         no       7   
...          ...     ...            ...     ...        ...     ...   
1397  5976-jcjrh    male              0     yes         no      10   
1398  2034-cgrhz    male              1      no         no      24   
1399  5276-kqwhg  female              1      no         no       2   
1407  6521-yytyi    male              0      no        yes       1   
1408  3049-solay  female              0     yes         no       3   

     phoneservice multiplelines internetservice onlinesecurity onlinebackup  \
3             yes            no     fiber_optic            yes           no   
8             yes            no     fiber_optic             no           no   
11            yes            no             dsl             no           no   
12            yes            no     fiber_optic             no           no   
19            yes           yes     fiber_optic             no           no   
...           ...           ...             ...            ...          ...   
1397          yes            no     fiber_optic             no           no   
1398          yes           yes     fiber_optic             no          yes   
1399          yes            no     fiber_optic             no           no   
1407          yes           yes     fiber_optic             no           no   
1408          yes           yes     fiber_optic             no           no   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
3                  no          no          no              no  month-to-month   
8                 yes         yes         yes             yes  month-to-month   
11                 no          no          no              no  month-to-month   
12                 no          no         yes             yes  month-to-month   
19                 no          no          no              no  month-to-month   
...               ...         ...         ...             ...             ...   
1397               no          no          no              no  month-to-month   
1398              yes          no         yes             yes  month-to-month   
1399               no          no          no              no  month-to-month   
1407               no          no         yes             yes  month-to-month   
1408               no          no         yes             yes  month-to-month   

     paperlessbilling            paymentmethod  monthlycharges  totalcharges  
3                 yes         electronic_check           75.70        189.20  
8                 yes             mailed_check           99.95        547.65  
11                yes             mailed_check           46.10        130.15  
12                yes         electronic_check           88.45        370.65  
19                yes         electronic_check           74.90        541.15  
...               ...                      ...             ...           ...  
1397              yes         electronic_check           70.30        738.20  
1398              yes  credit_card_(automatic)          102.95       2496.70  
1399              yes         electronic_check           69.60        131.65  
1407              yes         electronic_check           93.30         93.30  
1408              yes         electronic_check           95.20        292.85  

[311 rows x 20 columns]

In [179]:
df_val[churn_desc]['customerid']

3       8433-wxgna
8       3440-jpscl
11      2637-fkfsy
12      7228-omtpn
19      6711-fldfb
           ...    
1397    5976-jcjrh
1398    2034-cgrhz
1399    5276-kqwhg
1407    6521-yytyi
1408    3049-solay
Name: customerid, Length: 311, dtype: object

In [181]:
churn_desc

array([False, False, False, ..., False,  True,  True])

In [182]:
churn_desc.astype('int')

array([0, 0, 0, ..., 0, 1, 1])

In [184]:
(y_val == churn_desc.astype('int')).mean()

0.8034066713981547

In [185]:
model.score(X_val, y_val)

0.8034066713981547